In [14]:
#Importar librerias y cargar base de datos sucia
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/dianahdeztorres13-pixel/fh/main/j.csv")
df

Unnamed: 0  season  round   circuit_id weather_warm  weather_cold  \
0            14.0  1983.0    1.0       Auto%#        False           0.0   
1             5.0  1983.0    1.0  jacarepagua        False           0.0   
2             3.0  1983.0    NaN  jacarepagua        False           0.0   
3             0.0  1983.0    1.0  jacarepagua        False           0.0   
4             6.0  1983.0    1.0  jacarepagua        False           0.0   
...           ...     ...    ...          ...          ...           ...   
16636      4064.0  1993.0    1.0      kyalami         True           0.0   
16637      5893.0  1997.0   13.0        monza        False           0.0   
16638      9746.0  2008.0    7.0   villeneuve         True           0.0   
16639       434.0  1984.0    3.0       zolder        False           0.0   
16640      8554.0  2005.0    5.0    catalunya         True           0.0   

      weather_dry  weather_wet weather_cloudy        driver  ... grid podium  \
0            True          0.0          False  keke_rosberg  ...    1     15   
1            True          0.0          False         prost  ...    2      6   
2            True          0.0          False        tambay  ...    3      4   
3            True          0.0            NaN        piquet  ...    4      1   
4            True          0.0          False       warwick  ...    5      7   
...           ...          ...            ...           ...  ...  ...    ...   
16636       False          0.0          False      blundell  ...    8    NaN   
16637        True          0.0          False        irvine  ...   10      8   
16638       False          0.0          False    fisichella  ...   17     14   
16639       False          0.0          False        arnoux  ...    2      3   
16640       False          0.0          False     coulthard  ...    9      8   

      driver_points driver_wins  driver_standings_pos  constructor_points  \
0               0.0         0.0                   0.0                 0.0   
1               0.0         0.0                   0.0                 0.0   
2               0.0         0.0                   0.0                 0.0   
3               0.0         0.0                   0.0                 0.0   
4               0.0         0.0                   0.0                 0.0   
...             ...         ...                   ...                 ...   
16636           0.0         0.0                   0.0                 0.0   
16637          18.0         0.0                   6.0                84.0   
16638           0.0         0.0                  18.0                 0.0   
16639           0.0         0.0                  23.0                 0.0   
16640           9.0         0.0                   7.0                 NaN   

       constructor_wins  constructor_standings_pos  qualifying_time driver_age  
0                   0.0                          0              0.0       34.0  
1                   0.0                          0              0.2       28.0  
2                   0.0                          0              0.3       33.0  
3                   0.0                          0              0.6       30.0  
4                   0.0                          0              0.7       28.0  
...                 ...                        ...              ...        ...  
16636               0.0                        NaN              3.0       26.0  
16637               4.0                          1              0.9       31.0  
16638               0.0                         10              1.3       35.0  
16639               0.0                         11              0.6       35.0  
16640               0.0                          6              2.8       34.0  

[16641 rows x 22 columns]

In [15]:
#Creamos una copia para trabajar en ella
df2 = df

In [157]:
#Se verifica el tipo de dato registrado en cada columna para realizar el cambio de tipo en caso de ser necesario
df2.info

<bound method DataFrame.info of        Unnamed: 0  Sesion  Recorrido     Circuito Clima Calido  Clima frio  \
1             5.0  1983.0        1.0  jacarepagua        False         0.0   
4             6.0  1983.0        1.0  jacarepagua        False         0.0   
5             8.0  1983.0        1.0  jacarepagua        False         0.0   
6            22.0  1983.0        1.0  jacarepagua        False         0.0   
7            17.0  1983.0        1.0  jacarepagua        False         0.0   
...           ...     ...        ...          ...          ...         ...   
16633       299.0  1983.0       12.0    zandvoort        False         0.0   
16635     10066.0  2009.0        5.0    catalunya         True         0.0   
16637      5893.0  1997.0       13.0        monza        False         0.0   
16638      9746.0  2008.0        7.0   villeneuve         True         0.0   
16639       434.0  1984.0        3.0       zolder        False         0.0   

      Clima seco  Clima lluvioso Clima nublado      Piloto  ... Grilla Podio  \
1           True             0.0         False       prost  ...      2     6   
4           True             0.0         False     warwick  ...      5     7   
5           True             0.0         False      arnoux  ...      6     9   
6           True             0.0         False     patrese  ...      7    23   
7           True             0.0         False     cheever  ...      8    18   
...          ...             ...           ...         ...  ...    ...   ...   
16633      False             0.0          True     laffite  ...     17    20   
16635      False             0.0         False       sutil  ...     19    20   
16637       True             0.0         False      irvine  ...     10     8   
16638      False             0.0         False  fisichella  ...     17    14   
16639      False             0.0         False      arnoux  ...      2     3   

      Puntos_piloto Victorias_piloto  Posicion_piloto  Puntos_constructores  \
1               0.0              0.0              0.0                   0.0   
4               0.0              0.0              0.0                   0.0   
5               0.0              0.0              0.0                   0.0   
6               0.0              0.0              0.0                   0.0   
7               0.0              0.0              0.0                   0.0   
...             ...              ...              ...                   ...   
16633          11.0              0.0              9.0                  36.0   
16635           0.0              0.0             16.0                   0.0   
16637          18.0              0.0              6.0                  84.0   
16638           0.0              0.0             18.0                   0.0   
16639           0.0              0.0             23.0                   0.0   

       Victorias_constructores  Constructores_posicion  tiempo_clasificación  \
1                          0.0                       0                   0.2   
4                          0.0                       0                   0.7   
5                          0.0                       0                   1.0   
6                          0.0                       0                   1.5   
7                          0.0                       0                   1.6   
...                        ...                     ...                   ...   
16633                      1.0                       4                   4.4   
16635                      0.0                      10                   1.2   
16637                      4.0                       1                   0.9   
16638                      0.0                      10                   1.3   
16639                      0.0                      11                   0.6   

      Edad_piloto  
1            28.0  
4            28.0  
5            34.0  
6            28.0  
7            25.0  
...           ...  
16633        39.0  


In [17]:
#Se verifican las columnas con las que se cuenta
df.columns

Index(['Unnamed: 0', 'season', 'round', 'circuit_id', 'weather_warm',
       'weather_cold', 'weather_dry', 'weather_wet', 'weather_cloudy',
       'driver', 'nationality', 'constructor', 'grid', 'podium',
       'driver_points', 'driver_wins', 'driver_standings_pos',
       'constructor_points', 'constructor_wins', 'constructor_standings_pos',
       'qualifying_time', 'driver_age'],
      dtype='object')

In [158]:
#Conteo de datos nulos por columna
df.isnull().sum()

Unnamed: 0                   499
season                       499
round                        499
circuit_id                   499
weather_warm                 499
weather_cold                 824
weather_dry                  499
weather_wet                  822
weather_cloudy               499
driver                       499
nationality                  499
constructor                  499
grid                         499
podium                       499
driver_points                499
driver_wins                  499
driver_standings_pos         823
constructor_points           499
constructor_wins             499
constructor_standings_pos    499
qualifying_time              499
driver_age                   499
dtype: int64

In [159]:
#Tamaño del dataframe original
df.shape


(16641, 22)

In [160]:
#Visualizacion de datos duplicados
df.duplicated().sum()

np.int64(344)

In [162]:
#Renombramos las columnas a español
df2 = df2.rename(columns={"season":"Sesion","round":"Recorrido","circuit_id":"Circuito", "weather_warm":"Clima Calido", "weather_cold":"Clima frio","weather_dry":"Clima seco", "weather_wet":"Clima lluvioso",
                          "weather_cloudy":"Clima nublado","driver": "Piloto", "nationality": "Nacionalidad","grid":"Grilla","podium":"Podio",  "constructor":"Constructores", "driver_points":"Puntos_piloto",
       'driver_wins':"Victorias_piloto", 'driver_standings_pos':"Posicion_piloto", 'constructor_points':"Puntos_constructores",
       'constructor_wins':"Victorias_constructores", 'constructor_standings_pos': "Constructores_posicion", 'qualifying_time': "Tiempo_clasificación",
       'driver_age': "Edad_piloto"})
df2


Unnamed: 0  Sesion  Recorrido     Circuito Clima Calido  Clima frio  \
1             5.0  1983.0        1.0  jacarepagua        False         0.0   
4             6.0  1983.0        1.0  jacarepagua        False         0.0   
5             8.0  1983.0        1.0  jacarepagua        False         0.0   
6            22.0  1983.0        1.0  jacarepagua        False         0.0   
7            17.0  1983.0        1.0  jacarepagua        False         0.0   
...           ...     ...        ...          ...          ...         ...   
16633       299.0  1983.0       12.0    zandvoort        False         0.0   
16635     10066.0  2009.0        5.0    catalunya         True         0.0   
16637      5893.0  1997.0       13.0        monza        False         0.0   
16638      9746.0  2008.0        7.0   villeneuve         True         0.0   
16639       434.0  1984.0        3.0       zolder        False         0.0   

      Clima seco  Clima lluvioso Clima nublado      Piloto  ... Grilla Podio  \
1           True             0.0         False       prost  ...      2     6   
4           True             0.0         False     warwick  ...      5     7   
5           True             0.0         False      arnoux  ...      6     9   
6           True             0.0         False     patrese  ...      7    23   
7           True             0.0         False     cheever  ...      8    18   
...          ...             ...           ...         ...  ...    ...   ...   
16633      False             0.0          True     laffite  ...     17    20   
16635      False             0.0         False       sutil  ...     19    20   
16637       True             0.0         False      irvine  ...     10     8   
16638      False             0.0         False  fisichella  ...     17    14   
16639      False             0.0         False      arnoux  ...      2     3   

      Puntos_piloto Victorias_piloto  Posicion_piloto  Puntos_constructores  \
1               0.0              0.0              0.0                   0.0   
4               0.0              0.0              0.0                   0.0   
5               0.0              0.0              0.0                   0.0   
6               0.0              0.0              0.0                   0.0   
7               0.0              0.0              0.0                   0.0   
...             ...              ...              ...                   ...   
16633          11.0              0.0              9.0                  36.0   
16635           0.0              0.0             16.0                   0.0   
16637          18.0              0.0              6.0                  84.0   
16638           0.0              0.0             18.0                   0.0   
16639           0.0              0.0             23.0                   0.0   

       Victorias_constructores  Constructores_posicion  tiempo_clasificación  \
1                          0.0                       0                   0.2   
4                          0.0                       0                   0.7   
5                          0.0                       0                   1.0   
6                          0.0                       0                   1.5   
7                          0.0                       0                   1.6   
...                        ...                     ...                   ...   
16633                      1.0                       4                   4.4   
16635                      0.0                      10                   1.2   
16637                      4.0                       1                   0.9   
16638                      0.0                      10                   1.3   
16639                      0.0                      11                   0.6   

      Edad_piloto  
1            28.0  
4            28.0  
5            34.0  
6            28.0  
7            25.0  
...           ...  
16633        39.0  
16635        26.0  
16637        31.0  

In [ ]:
#Se procede a eliminar

In [26]:
df2["Sesion"].unique()

array([1983.,   nan, 1984., 1985., 1986., 1987., 1988., 1989., 1990.,
       1991., 1992., 1993., 1994., 1995., 1996., 1997., 1998., 1999.,
       2000., 2001., 2002., 2003., 2004., 2005., 2006., 2007., 2008.,
       2009., 2010., 2011., 2012., 2013., 2014., 2015., 2016., 2017.,
       2018., 2019., 2020., 2021.])

In [28]:
df2["Sesion"].isnull().sum()

np.int64(481)

In [29]:
df2 = df2[df2["Sesion"].notna()]

In [30]:
df2["Sesion"].unique()

array([1983., 1984., 1985., 1986., 1987., 1988., 1989., 1990., 1991.,
       1992., 1993., 1994., 1995., 1996., 1997., 1998., 1999., 2000.,
       2001., 2002., 2003., 2004., 2005., 2006., 2007., 2008., 2009.,
       2010., 2011., 2012., 2013., 2014., 2015., 2016., 2017., 2018.,
       2019., 2020., 2021.])

In [19]:
df2["Recorrido"].unique()

array([ 1., nan,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21.])

In [20]:
df2["Recorrido"].isnull().sum()

np.int64(499)

In [22]:
df2 = df2[df2["Recorrido"].notna()]

In [25]:
df2["Recorrido"].unique()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21.])

In [33]:
df2["Circuito"].unique()

array(['Auto%#', 'jacarepagua', nan, 'long_beach', 'ricard', 'imola',
       'monaco', 'spa', 'detroit', 'villeneuve', 'silverstone',
       'hockenheimring', 'osterreichring', 'zandvoort', 'monza',
       'brands_hatch', 'kyalami', 'zolder', 'dijon', 'dallas',
       'nurburgring', 'estoril', 'adelaide', 'jerez', 'hungaroring',
       'rodriguez', 'suzuka', 'phoenix', 'interlagos', 'magny_cours',
       'catalunya', 'donington', 'okayama', 'galvez', 'albert_park',
       'sepang', 'indianapolis', 'bahrain', 'shanghai', 'istanbul',
       'fuji', 'valencia', 'marina_bay', 'yas_marina', 'yeongam', 'buddh',
       'americas', 'red_bull_ring', 'sochi', 'BAK', 'mugello', 'portimao'],
      dtype=object)

In [34]:
df2["Circuito"].isnull().sum()

np.int64(467)

In [41]:
df2 = df2[df2["Circuito"] != "Auto%#"]

In [38]:
df2["Circuito"].unique()

array(['jacarepagua', 'long_beach', 'ricard', 'imola', 'monaco', 'spa',
       'detroit', 'villeneuve', 'silverstone', 'hockenheimring',
       'osterreichring', 'zandvoort', 'monza', 'brands_hatch', 'kyalami',
       'zolder', 'dijon', 'dallas', 'nurburgring', 'estoril', 'adelaide',
       'jerez', 'hungaroring', 'rodriguez', 'suzuka', 'phoenix',
       'interlagos', 'magny_cours', 'catalunya', 'donington', 'okayama',
       'galvez', 'albert_park', 'sepang', 'indianapolis', 'bahrain',
       'shanghai', 'istanbul', 'fuji', 'valencia', 'marina_bay',
       'yas_marina', 'yeongam', 'buddh', 'americas', 'red_bull_ring',
       'sochi', 'BAK', 'mugello', 'portimao'], dtype=object)

In [40]:
df2["Clima Calido"].unique()

array([False, True, nan], dtype=object)

In [42]:
df2["Clima Calido"].isnull().sum()

np.int64(443)

In [45]:
df2 = df2[df2["Clima Calido"].notna()]

In [46]:
df2["Clima Calido"].unique()

array([False, True], dtype=object)

In [48]:
df2["Clima frio"].unique()

array([ 0., nan,  1.])

In [49]:
df2["Clima frio"].isnull().sum()

np.int64(720)

In [50]:
df2 = df2[df2["Clima frio"].notna()]

In [51]:
df2["Clima frio"].unique()

array([0., 1.])

In [52]:
df2["Clima seco"].unique()

array(['True', nan, 'False', 'Auto%#'], dtype=object)

In [53]:
df2["Clima seco"].isnull().sum()

np.int64(411)

In [56]:
df2 = df2[(df2["Clima seco"] != "Auto%#") & (df2["Clima seco"].notna())]

In [57]:
df2["Clima seco"].unique()

array(['True', 'False'], dtype=object)

In [58]:
df2["Clima lluvioso"].unique()

array([ 0.,  1., nan])

In [60]:
df2["Clima lluvioso"].isnull().sum()

np.int64(635)

In [61]:
df2 = df2[df2["Clima lluvioso"].notna()]

In [62]:
df2["Clima lluvioso"].unique()

array([0., 1.])

In [63]:
df2["Clima nublado"].unique()

array(['False', nan, 'Auto%#', 'True'], dtype=object)

In [64]:
df2["Clima nublado"].isnull().sum()

np.int64(362)

In [65]:
df2 = df2[(df2["Clima nublado"] != "Auto%#") & (df2["Clima nublado"].notna())]

In [66]:
df2["Clima nublado"].unique()

array(['False', 'True'], dtype=object)

In [67]:
df2["Piloto"].unique()

array(['prost', 'warwick', 'arnoux', 'patrese', 'cheever', 'lauda',
       'jarier', 'guerrero', 'watson', 'boesel', 'laffite', 'cecotto',
       'surer', 'sullivan', 'mansell', 'serra', 'salazar', 'tambay', nan,
       'alboreto', 'jones', 'giacomelli', 'cesaris', 'baldi',
       'manfred_winkelhock', 'angelis', 'corrado_fabi', 'piquet',
       'keke_rosberg', 'ghinzani', 'boutsen', 'johansson', 'palmer',
       'acheson', 'senna', 'brundle', 'hesnault', 'bellof', 'fabi',
       'alliot', 'rothengatter', 'berger', 'gartner', 'streiff',
       'martini', 'danner', 'capelli', 'dumfries', 'nannini', 'berg',
       'satoru_nakajima', 'fabre', 'campos', 'caffi', 'tarquini',
       'forini', 'larini', 'dalmas', 'sala', 'modena', 'larrauri',
       'gugelmin', 'bailey', 'schneider', 'suzuki', 'grouillard',
       'raphanel', 'herbert', 'moreno', 'bernard', 'alesi', 'pirro',
       'gachot', 'lehto', 'barilla', 'donnelly', 'foitek', 'morbidelli',
       'brabham', 'blundell', 'hakkinen', 'com

In [68]:
df2["Nacionalidad"].unique()

array(['French', 'British', 'Italian', 'American', 'Austrian',
       'Colombian', 'Brazilian', 'Venezuelan', 'Swiss', 'Chilean',
       'Finnish', 'Australian', 'German', 'Auto%#', nan, 'Belgian',
       'Swedish', 'Dutch', 'Canadian', 'Japanese', 'Spanish', 'Argentine',
       'Portuguese', 'Monegasque', 'Danish', 'Czech', 'Malaysian',
       'Irish', 'Hungarian', 'Indian', 'Polish', 'Russian', 'Mexican',
       'Indonesian', 'New Zealander', 'Thai'], dtype=object)

In [69]:
df2["Nacionalidad"].isnull().sum()

np.int64(340)

In [71]:
df2 = df2[(df2["Nacionalidad"] != "Auto%#") & (df2["Nacionalidad"].notna())]


In [72]:
df2["Nacionalidad"].unique()

array(['French', 'British', 'Italian', 'American', 'Austrian',
       'Colombian', 'Brazilian', 'Venezuelan', 'Swiss', 'Chilean',
       'Finnish', 'Australian', 'German', 'Belgian', 'Swedish', 'Dutch',
       'Canadian', 'Japanese', 'Spanish', 'Argentine', 'Portuguese',
       'Monegasque', 'Danish', 'Czech', 'Malaysian', 'Irish', 'Hungarian',
       'Indian', 'Polish', 'Russian', 'Mexican', 'Indonesian',
       'New Zealander', 'Thai'], dtype=object)

In [74]:
df2["Constructores"].unique()

array(['renault', 'toleman', 'ferrari', nan, 'mclaren', 'ligier',
       'theodore', 'williams', 'arrows', 'tyrrell', 'team_lotus',
       'Auto%#', 'ram', 'alfa', 'ats', 'brabham', 'osella', 'spirit',
       'minardi', 'zakspeed', 'lola', 'benetton', 'ags', 'march',
       'larrousse', 'coloni', 'rial', 'eurobrun', 'dallara', 'onyx',
       'leyton', 'lambo', 'footwork', 'jordan', 'fondmetal', 'moda',
       'sauber', 'simtek', 'pacific', 'forti', 'prost', 'stewart', 'bar',
       'jaguar', 'toyota', 'red_bull', 'honda', 'bmw_sauber',
       'toro_rosso', 'mf1', 'super_aguri', 'spyker_mf1', 'spyker',
       'force_india', 'brawn', 'mercedes', 'lotus_racing', 'virgin',
       'hrt', 'lotus_f1', 'caterham', 'marussia', 'manor', 'haas',
       'racing_point', 'alphatauri', 'alpine', 'aston_martin'],
      dtype=object)

In [75]:
df2["Constructores"].isnull().sum()

np.int64(324)

In [77]:
df2 = df2[df2["Constructores"] != "Auto%#"]


In [78]:
df2["Constructores"].unique()

array(['renault', 'toleman', 'ferrari', nan, 'mclaren', 'ligier',
       'theodore', 'williams', 'arrows', 'tyrrell', 'team_lotus', 'ram',
       'alfa', 'ats', 'brabham', 'osella', 'spirit', 'minardi',
       'zakspeed', 'lola', 'benetton', 'ags', 'march', 'larrousse',
       'coloni', 'rial', 'eurobrun', 'dallara', 'onyx', 'leyton', 'lambo',
       'footwork', 'jordan', 'fondmetal', 'moda', 'sauber', 'simtek',
       'pacific', 'forti', 'prost', 'stewart', 'bar', 'jaguar', 'toyota',
       'red_bull', 'honda', 'bmw_sauber', 'toro_rosso', 'mf1',
       'super_aguri', 'spyker_mf1', 'spyker', 'force_india', 'brawn',
       'mercedes', 'lotus_racing', 'virgin', 'hrt', 'lotus_f1',
       'caterham', 'marussia', 'manor', 'haas', 'racing_point',
       'alphatauri', 'alpine', 'aston_martin'], dtype=object)

In [80]:
df2["Grilla"].unique()

array(['2', '5', '6', '7', '8', '9', '12', '14', '16', '17', '18', '19',
       '20', '21', '22', '26', '1', '3', '4', '10', nan, '15', '24', '25',
       '23', '11', 'Auto%#', '13', '27'], dtype=object)

In [82]:
df2["Grilla"].isnull().sum()

np.int64(328)

In [83]:
df2 = df2[(df2["Grilla"] != "Auto%#") & (df2["Grilla"].notna())]


In [84]:
df2["Grilla"].unique()

array(['2', '5', '6', '7', '8', '9', '12', '14', '16', '17', '18', '19',
       '20', '21', '22', '26', '1', '3', '4', '10', '15', '24', '25',
       '23', '11', '13', '27'], dtype=object)

In [85]:
df2["Podio"].unique()

array(['6', '7', '9', '23', '18', '2', '22', '17', '19', '20', '3', '12',
       '5', '10', '11', '13', '4', '14', '16', '21', '1', '26', '24', '8',
       '25', 'Auto%#', '15', nan, '27'], dtype=object)

In [86]:
df2["Podio"].isnull().sum()

np.int64(315)

In [87]:
df2 = df2[(df2["Podio"] != "Auto%#") & (df2["Podio"].notna())]


In [88]:
df2["Podio"].unique()

array(['6', '7', '9', '23', '18', '2', '22', '17', '19', '20', '3', '12',
       '5', '10', '11', '13', '4', '14', '16', '21', '1', '26', '24', '8',
       '25', '15', '27'], dtype=object)

In [95]:
df2["Puntos_piloto"].unique()

array([  0.,   2.,   3.,   1.,   4.,  10.,   9.,   6.,  15.,   5.,   8.,
         7.,  19.,  14.,  16.,  11.,  28.,  27.,  23.,  22.,  17.,  30.,
        33.,  39.,  25.,  42.,  37.,  31.,  51.,  34.,  18.,  43.,  12.,
        46.,  40.,  21.,  55.,  49.,  13.,  24.,  29.,  32.,  63.,  20.,
        35.,  26.,  53.,  65.,  38.,  36.,  47.,  44.,  48.,  61.,  56.,
        70.,  59.,  64.,  41.,  67.,  52.,  73.,  57.,  54.,  60.,  66.,
        75.,  72.,  76.,  79.,  84.,  87.,  71.,  50.,  78.,  69.,  77.,
        85.,  91.,  86.,  98., 108.,  45.,  58.,  62.,  93.,  81.,  82.,
        68.,  74.,  80.,  88.,  94., 113., 106.,  83.,  90., 100., 120.,
       136., 111., 117., 123., 104.,  89.,  96., 116.,  97., 107.,  95.,
       103., 109., 115., 127., 133., 157., 143., 161., 147., 141., 151.,
       166., 163., 165., 187., 112., 181., 202., 114., 191., 177., 122.,
       182., 128., 206., 210., 231., 189., 222., 246., 130., 118., 101.,
       186., 204., 216., 139., 146., 134., 259., 14

In [96]:
df2["Puntos_piloto"].isnull().sum()

np.int64(0)

In [97]:
df2 = df2[df2["Puntos_piloto"].notna()]


In [98]:
df2["Puntos_piloto"].unique()

array([  0.,   2.,   3.,   1.,   4.,  10.,   9.,   6.,  15.,   5.,   8.,
         7.,  19.,  14.,  16.,  11.,  28.,  27.,  23.,  22.,  17.,  30.,
        33.,  39.,  25.,  42.,  37.,  31.,  51.,  34.,  18.,  43.,  12.,
        46.,  40.,  21.,  55.,  49.,  13.,  24.,  29.,  32.,  63.,  20.,
        35.,  26.,  53.,  65.,  38.,  36.,  47.,  44.,  48.,  61.,  56.,
        70.,  59.,  64.,  41.,  67.,  52.,  73.,  57.,  54.,  60.,  66.,
        75.,  72.,  76.,  79.,  84.,  87.,  71.,  50.,  78.,  69.,  77.,
        85.,  91.,  86.,  98., 108.,  45.,  58.,  62.,  93.,  81.,  82.,
        68.,  74.,  80.,  88.,  94., 113., 106.,  83.,  90., 100., 120.,
       136., 111., 117., 123., 104.,  89.,  96., 116.,  97., 107.,  95.,
       103., 109., 115., 127., 133., 157., 143., 161., 147., 141., 151.,
       166., 163., 165., 187., 112., 181., 202., 114., 191., 177., 122.,
       182., 128., 206., 210., 231., 189., 222., 246., 130., 118., 101.,
       186., 204., 216., 139., 146., 134., 259., 14

In [99]:
df2["Puntos_piloto"].unique()

array([  0.,   2.,   3.,   1.,   4.,  10.,   9.,   6.,  15.,   5.,   8.,
         7.,  19.,  14.,  16.,  11.,  28.,  27.,  23.,  22.,  17.,  30.,
        33.,  39.,  25.,  42.,  37.,  31.,  51.,  34.,  18.,  43.,  12.,
        46.,  40.,  21.,  55.,  49.,  13.,  24.,  29.,  32.,  63.,  20.,
        35.,  26.,  53.,  65.,  38.,  36.,  47.,  44.,  48.,  61.,  56.,
        70.,  59.,  64.,  41.,  67.,  52.,  73.,  57.,  54.,  60.,  66.,
        75.,  72.,  76.,  79.,  84.,  87.,  71.,  50.,  78.,  69.,  77.,
        85.,  91.,  86.,  98., 108.,  45.,  58.,  62.,  93.,  81.,  82.,
        68.,  74.,  80.,  88.,  94., 113., 106.,  83.,  90., 100., 120.,
       136., 111., 117., 123., 104.,  89.,  96., 116.,  97., 107.,  95.,
       103., 109., 115., 127., 133., 157., 143., 161., 147., 141., 151.,
       166., 163., 165., 187., 112., 181., 202., 114., 191., 177., 122.,
       182., 128., 206., 210., 231., 189., 222., 246., 130., 118., 101.,
       186., 204., 216., 139., 146., 134., 259., 14

In [101]:
df2["Victorias_piloto"].unique()

array([ 0., nan,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 12.,
       11., 13.])

In [104]:
df2["Victorias_piloto"].isnull().sum()

np.int64(289)

In [105]:
df2 = df2[df2["Victorias_piloto"].notna()]


In [106]:
df2["Victorias_piloto"].unique()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 12., 11.,
       13.])

In [107]:
df2["Posicion_piloto"].unique()

array([ 0.,  4.,  9.,  3., 24., 20., 16.,  5., 12., 15., 25., 19., 17.,
       14., 13., nan, 23., 21., 26.,  1., 22., 28., 11., 10.,  7.,  6.,
        8.,  2., 18., 27., 29., 30.])

In [108]:
df2["Posicion_piloto"].isnull().sum()

np.int64(446)

In [109]:
df2 = df2[df2["Posicion_piloto"].notna()]


In [110]:
df2["Posicion_piloto"].unique()

array([ 0.,  4.,  9.,  3., 24., 20., 16.,  5., 12., 15., 25., 19., 17.,
       14., 13., 23., 21., 26.,  1., 22., 28., 11., 10.,  7.,  6.,  8.,
        2., 18., 27., 29., 30.])

In [111]:
df2["Puntos_constructores"].unique()

array([  0.,   2.,   3.,   1.,   4.,   6.,  19.,   9.,  15.,  13.,  22.,
        nan,  23.,  21.,  24.,  31.,  36.,  27.,  32.,  11.,  25.,  44.,
        26.,  53.,  33.,  35.,  59.,  37.,  56.,   7.,  29.,  41.,  65.,
        68.,  30.,  80.,  34.,  12.,   8.,  50.,  89.,  72.,  10.,  17.,
         5.,  38.,  45.,  16.,  47.,  55.,  43.,  49.,  75.,  70.,  79.,
        54.,  63.,  77.,  83.,  71.,  62.,  18.,  46.,  48.,  61.,  60.,
        42.,  28., 102., 117., 130.,  81., 135.,  57.,  87.,  69.,  78.,
        93.,  51.,  20., 110., 122., 137.,  76.,  64., 132., 147., 157.,
       169., 184.,  98.,  52., 128., 141.,  14.,  96.,  40., 109., 118.,
       100.,  67.,  99., 108., 114., 116.,  58.,  74.,  84., 126., 142.,
       144.,  73., 154.,  85.,  39., 129., 139., 149.,  95.,  97., 103.,
        94., 104., 133., 101., 111., 165.,  86.,  90.,  92., 125., 106.,
        66.,  82.,  88., 127., 143., 153., 156., 140., 167., 205., 121.,
       120., 124., 158., 174.,  91., 202., 216., 24

In [142]:
df2["Puntos_constructores"].isnull().sum()

np.int64(241)

In [143]:
df2 = df2[df2["Puntos_constructores"].notna()]

In [144]:
df2["Puntos_constructores"].unique()

array([  0.,   2.,   3.,   1.,   4.,   6.,  19.,   9.,  15.,  13.,  22.,
        23.,  21.,  24.,  31.,  36.,  27.,  32.,  11.,  25.,  44.,  26.,
        53.,  35.,  59.,  37.,  56.,   7.,  29.,  41.,  68.,  65.,  80.,
        34.,  12.,   8.,  50.,  89.,  72.,  10.,  17.,   5.,  38.,  33.,
        45.,  16.,  47.,  55.,  43.,  49.,  79.,  54.,  77.,  83.,  71.,
        62.,  18.,  46.,  48.,  60.,  63.,  42.,  28., 102., 117.,  75.,
       130.,  81., 135.,  57.,  87.,  30.,  69.,  78.,  93.,  51.,  20.,
       110., 122., 137.,  76.,  64., 132., 147., 157., 169., 184.,  98.,
        52., 128., 141.,  14.,  96.,  40., 109., 118., 100.,  70.,  99.,
       108., 114., 116.,  58.,  74.,  84., 142., 144.,  73., 154.,  85.,
       129., 139., 149.,  67.,  95.,  97., 103.,  94., 133., 101.,  61.,
       165.,  86.,  39.,  90.,  92., 106.,  66.,  82.,  88., 127., 143.,
       140., 167., 205., 121., 120., 124., 174.,  91., 202., 216., 244.,
       105., 136., 152., 146., 164., 176., 131., 15

In [112]:
df2["Victorias_constructores"].unique()

array([ 0., nan,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,
       12., 13., 14., 15., 16., 17., 18.])

In [113]:
df2["Victorias_constructores"].isnull().sum()

np.int64(289)

In [114]:
df2 = df2[df2["Victorias_constructores"].notna()]


In [115]:
df2["Victorias_constructores"].unique()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18.])

In [116]:
df2["Constructores_posicion"].unique()

array(['0', '4', '3', '8', '13', '5', '6', '10', '14', '2', nan, '11',
       '1', '9', 'Auto%#', '12', '7', '15', '16', '17', '18', '19', '20'],
      dtype=object)

In [118]:
df2["Constructores_posicion"].isnull().sum()

np.int64(254)

In [119]:
df2 = df2[(df2["Constructores_posicion"] != "Auto%#") & (df2["Constructores_posicion"].notna())]

In [120]:
df2["Constructores_posicion"].unique()

array(['0', '4', '3', '8', '13', '5', '6', '10', '14', '2', '11', '1',
       '9', '12', '7', '15', '16', '17', '18', '19', '20'], dtype=object)

In [137]:
df2["tiempo_clasificación"].unique()

array([ 2.000e-01,  7.000e-01,  1.000e+00,  1.500e+00,  1.600e+00,
        1.900e+00,  2.200e+00,  2.500e+00,  3.200e+00,  3.700e+00,
        4.200e+00,  4.700e+00,  7.000e+00,  0.000e+00,  8.000e-01,
        1.700e+00,  2.300e+00,  2.800e+00,  3.000e+00,  3.300e+00,
        3.500e+00,  4.000e+00,  5.000e+00,  2.400e+00,  2.600e+00,
        2.900e+00,  4.400e+00,  5.100e+00,  5.500e+00,  6.700e+00,
        7.800e+00,  8.100e+00,  8.000e-01,  9.000e-01,  2.300e+00,
        3.800e+00,  4.500e+00,  6.500e+00,  4.000e-01,  4.400e+00,
        3.400e+00,  4.600e+00,  4.700e+00,  4.900e+00,  5.300e+00,
        6.800e+00,  7.100e+00,  2.000e+00,  2.800e+00,  4.300e+00,
        4.800e+00,  5.200e+00,  1.000e-01,  1.200e+00,  3.100e+00,
        3.900e+00,  4.900e+00,  5.600e+00,  5.800e+00,  6.000e-01,
        2.700e+00,  3.900e+00,  5.900e+00,  6.100e+00,  6.300e+00,
        1.000e-01,  5.300e+00,  6.000e+00,  7.200e+00,  7.400e+00,
        7.700e+00,  9.100e+00,  7.000e-01,  1.800e+00,  6.600e

In [138]:
df2["tiempo_clasificación"].isnull().sum()

np.int64(0)

In [139]:
df2 = df2[df2["tiempo_clasificación"].notna()]


In [140]:
df2["tiempo_clasificación"].unique()

array([ 2.000e-01,  7.000e-01,  1.000e+00,  1.500e+00,  1.600e+00,
        1.900e+00,  2.200e+00,  2.500e+00,  3.200e+00,  3.700e+00,
        4.200e+00,  4.700e+00,  7.000e+00,  0.000e+00,  8.000e-01,
        1.700e+00,  2.300e+00,  2.800e+00,  3.000e+00,  3.300e+00,
        3.500e+00,  4.000e+00,  5.000e+00,  2.400e+00,  2.600e+00,
        2.900e+00,  4.400e+00,  5.100e+00,  5.500e+00,  6.700e+00,
        7.800e+00,  8.100e+00,  8.000e-01,  9.000e-01,  2.300e+00,
        3.800e+00,  4.500e+00,  6.500e+00,  4.000e-01,  4.400e+00,
        3.400e+00,  4.600e+00,  4.700e+00,  4.900e+00,  5.300e+00,
        6.800e+00,  7.100e+00,  2.000e+00,  2.800e+00,  4.300e+00,
        4.800e+00,  5.200e+00,  1.000e-01,  1.200e+00,  3.100e+00,
        3.900e+00,  4.900e+00,  5.600e+00,  5.800e+00,  6.000e-01,
        2.700e+00,  3.900e+00,  5.900e+00,  6.100e+00,  6.300e+00,
        1.000e-01,  5.300e+00,  6.000e+00,  7.200e+00,  7.400e+00,
        7.700e+00,  9.100e+00,  7.000e-01,  1.800e+00,  6.600e

In [125]:
df2["Edad_piloto"].unique()

array([28., 34., 25., 36., 24., 39., 33., 29., 26., 27., 23., 30., 31.,
       22., 37., 35., nan, 32., 40., 41., 38., 42., 21., 20., 19., 43.,
       17., 18.])

In [126]:
df2["Edad_piloto"].isnull().sum()

np.int64(241)

In [127]:
df2 = df2[df2["Edad_piloto"].notna()]


In [128]:
df2["Edad_piloto"].unique()

array([28., 34., 25., 36., 24., 39., 33., 29., 26., 27., 23., 30., 31.,
       22., 37., 35., 32., 40., 41., 38., 42., 21., 20., 19., 43., 17.,
       18.])

In [136]:
df2.columns

Index(['Unnamed: 0', 'Sesion', 'Recorrido', 'Circuito', 'Clima Calido',
       'Clima frio', 'Clima seco', 'Clima lluvioso', 'Clima nublado', 'Piloto',
       'Nacionalidad', 'Constructores', 'Grilla', 'Podio', 'Puntos_piloto',
       'Victorias_piloto', 'Posicion_piloto', 'Puntos_constructores',
       'Victorias_constructores', 'Constructores_posicion',
       'tiempo_clasificación', 'Edad_piloto'],
      dtype='object')

In [145]:
df2

Unnamed: 0  Sesion  Recorrido     Circuito Clima Calido  Clima frio  \
1             5.0  1983.0        1.0  jacarepagua        False         0.0   
4             6.0  1983.0        1.0  jacarepagua        False         0.0   
5             8.0  1983.0        1.0  jacarepagua        False         0.0   
6            22.0  1983.0        1.0  jacarepagua        False         0.0   
7            17.0  1983.0        1.0  jacarepagua        False         0.0   
...           ...     ...        ...          ...          ...         ...   
16633       299.0  1983.0       12.0    zandvoort        False         0.0   
16635     10066.0  2009.0        5.0    catalunya         True         0.0   
16637      5893.0  1997.0       13.0        monza        False         0.0   
16638      9746.0  2008.0        7.0   villeneuve         True         0.0   
16639       434.0  1984.0        3.0       zolder        False         0.0   

      Clima seco  Clima lluvioso Clima nublado      Piloto  ... Grilla Podio  \
1           True             0.0         False       prost  ...      2     6   
4           True             0.0         False     warwick  ...      5     7   
5           True             0.0         False      arnoux  ...      6     9   
6           True             0.0         False     patrese  ...      7    23   
7           True             0.0         False     cheever  ...      8    18   
...          ...             ...           ...         ...  ...    ...   ...   
16633      False             0.0          True     laffite  ...     17    20   
16635      False             0.0         False       sutil  ...     19    20   
16637       True             0.0         False      irvine  ...     10     8   
16638      False             0.0         False  fisichella  ...     17    14   
16639      False             0.0         False      arnoux  ...      2     3   

      Puntos_piloto Victorias_piloto  Posicion_piloto  Puntos_constructores  \
1               0.0              0.0              0.0                   0.0   
4               0.0              0.0              0.0                   0.0   
5               0.0              0.0              0.0                   0.0   
6               0.0              0.0              0.0                   0.0   
7               0.0              0.0              0.0                   0.0   
...             ...              ...              ...                   ...   
16633          11.0              0.0              9.0                  36.0   
16635           0.0              0.0             16.0                   0.0   
16637          18.0              0.0              6.0                  84.0   
16638           0.0              0.0             18.0                   0.0   
16639           0.0              0.0             23.0                   0.0   

       Victorias_constructores  Constructores_posicion  tiempo_clasificación  \
1                          0.0                       0                   0.2   
4                          0.0                       0                   0.7   
5                          0.0                       0                   1.0   
6                          0.0                       0                   1.5   
7                          0.0                       0                   1.6   
...                        ...                     ...                   ...   
16633                      1.0                       4                   4.4   
16635                      0.0                      10                   1.2   
16637                      4.0                       1                   0.9   
16638                      0.0                      10                   1.3   
16639                      0.0                      11                   0.6   

      Edad_piloto  
1            28.0  
4            28.0  
5            34.0  
6            28.0  
7            25.0  
...           ...  
16633        39.0  
16635        26.0  
16637        31.0  

In [149]:
df2.to_csv("df2_limpio.csv", index=False)


In [151]:
!ls -l df2_limpio.csv


-rw-r--r-- 1 root root 952760 Oct 21 05:07 df2_limpio.csv


In [152]:
from google.colab import files

In [153]:
files.download("df2_limpio.csv")


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>